version: '3.0'

services:
  check_ip:
    build: ./front-proxy
    restart: always
    networks:
      - backend
    environment:
      - PROXY_SERVICE=socks5://tors:9050
      - DST_SERVICE=http://ifconfig.me
      - SERVICE_ADDR=0.0.0.0:8080
    expose:
      - "8080"
    ports:
      - "19090:8080"

  iinstagram:
    build: ./front-proxy
    restart: always
    networks:
       - backend
    environment:
      - PROXY_SERVICE=socks5://tors:9050
      - DST_SERVICE=https://i.instagram.com
      - SERVICE_ADDR=0.0.0.0:8080
    expose:
      - "8080"
    ports:
      - "19091:8080"

  main_svc:
    build: ./front-proxy
    restart: always
    networks:
      - backend
    environment:
      - PROXY_SERVICE=socks5://tors:9050
      - DST_SERVICE=https://nhentai.net
      - SERVICE_ADDR=0.0.0.0:8080
    expose:
      - "8080"
    ports:
      - "16060:8080"
  static_svc:
    build: ./front-proxy
    restart: always
    networks:
      - backend
    environment:
      - PROXY_SERVICE=socks5://tors:9050
      - DST_SERVICE=https://static.nhentai.net
      - SERVICE_ADDR=0.0.0.0:8080
    expose:
      - "8080"
    ports:
      - "16061:8080"
  t_img:
    build: ./front-proxy
    restart: always
    networks:
      - backend
    environment:
      - PROXY_SERVICE=socks5://tors:9050
      - DST_SERVICE=https://t.nhentai.net
      - SERVICE_ADDR=0.0.0.0:8080
    expose:
      - "8080"
    ports:
      - "18080:8080"

  i_img:
     build: ./front-proxy
     restart: always
     networks:
      - backend
     environment:
      - PROXY_SERVICE=socks5://tors:9050
      - DST_SERVICE=https://i.nhentai.net
      - SERVICE_ADDR=0.0.0.0:8080
     expose:
      - "8080"
     ports:
      - "18081:8080"
    
  tor:
    build: ./tor-s
    networks:
       backend:
         aliases:
          - tors
    expose:
     - "5000"
     - "9050"


networks:
  backend: {}
