version: '3.0'

services:
  t_img:
    build: ./front-proxy
    links:
      - tor-s
    environment:
      - PROXY_SERVICE=socks5://tor-s:9050
      - DST_SERVICE=https://t.nhentai.net
      - SERVICE_ADDR=0.0.0.0:8080
    expose:
      - "8080"
    ports:
      - "18080:8080"

  i_img:
     build: ./front-proxy
     links:
       - tor-s
     environment:
      - PROXY_SERVICE=socks5://tor-s:9050
      - DST_SERVICE=https://i.nhentai.net
      - SERVICE_ADDR=0.0.0.0:8080
     expose:
      - "8080"
     ports:
      - "18081:8080"
    
  tor-s:
    build: ./tor-s
    expose:
     - "5000"
     - "9050"
